/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Account`; params?: Router.UnknownInputParams; } | { pathname: `/GetStarted`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/Splash`; params?: Router.UnknownInputParams; } | { pathname: `/../components/sections/HomeSection`; params?: Router.UnknownInputParams; } | { pathname: `/../components/sections/AccountSection`; params?: Router.UnknownInputParams; } | { pathname: `/../components/sections/SettingsSection`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/interview/form`; params?: Router.UnknownInputParams; } | { pathname: `/interview/question`; params?: Router.UnknownInputParams; } | { pathname: `/interview/questions`; params?: Router.UnknownInputParams; } | { pathname: `/resume/form`; params?: Router.UnknownInputParams; } | { pathname: `/resume/preview`; params?: Router.UnknownInputParams; } | { pathname: `/resume/result`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Account`; params?: Router.UnknownOutputParams; } | { pathname: `/GetStarted`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/Splash`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/sections/HomeSection`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/sections/AccountSection`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/sections/SettingsSection`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/interview/form`; params?: Router.UnknownOutputParams; } | { pathname: `/interview/question`; params?: Router.UnknownOutputParams; } | { pathname: `/interview/questions`; params?: Router.UnknownOutputParams; } | { pathname: `/resume/form`; params?: Router.UnknownOutputParams; } | { pathname: `/resume/preview`; params?: Router.UnknownOutputParams; } | { pathname: `/resume/result`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Account${`?${string}` | `#${string}` | ''}` | `/GetStarted${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/Splash${`?${string}` | `#${string}` | ''}` | `/../components/sections/HomeSection${`?${string}` | `#${string}` | ''}` | `/../components/sections/AccountSection${`?${string}` | `#${string}` | ''}` | `/../components/sections/SettingsSection${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/interview/form${`?${string}` | `#${string}` | ''}` | `/interview/question${`?${string}` | `#${string}` | ''}` | `/interview/questions${`?${string}` | `#${string}` | ''}` | `/resume/form${`?${string}` | `#${string}` | ''}` | `/resume/preview${`?${string}` | `#${string}` | ''}` | `/resume/result${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Account`; params?: Router.UnknownInputParams; } | { pathname: `/GetStarted`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/Splash`; params?: Router.UnknownInputParams; } | { pathname: `/../components/sections/HomeSection`; params?: Router.UnknownInputParams; } | { pathname: `/../components/sections/AccountSection`; params?: Router.UnknownInputParams; } | { pathname: `/../components/sections/SettingsSection`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/interview/form`; params?: Router.UnknownInputParams; } | { pathname: `/interview/question`; params?: Router.UnknownInputParams; } | { pathname: `/interview/questions`; params?: Router.UnknownInputParams; } | { pathname: `/resume/form`; params?: Router.UnknownInputParams; } | { pathname: `/resume/preview`; params?: Router.UnknownInputParams; } | { pathname: `/resume/result`; params?: Router.UnknownInputParams; };
    }
  }
}
